/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.stri.tchat;

import ContenuSalonetClient.Client;
import ContenuSalonetClient.Salon;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *https://github.com/ElhadjDiallo/Projet-Java-Etudiant.git
 * @author elhadj
 */
public class IhmSalon extends javax.swing.JPanel {

    /**
     * Creates new form IhmSalon
     */
    private ListeduContenuDunSalonIhm listModelIhm;
   
    public IhmSalon(Salon salon) {
       
       listModelIhm=new ListeduContenuDunSalonIhm(salon.getNom());
        initComponents();
          listModelIhm.ajouter(salon);
        this.setName(salon.getNom());
       listContenuSalonIhmCellrendere();
        
    }
    public void afficher(String texte)
    {
        affichageContenu.setText(texte);
    }
    public String getNom()
    {
        return this.getName();
    }
    
    public void listContenuSalonIhmCellrendere()
    {
       jlistIhm.setCellRenderer(new ListCellRenderer<Client>() {

           @Override
           public Component getListCellRendererComponent(JList<? extends Client> list, Client value, int index, boolean isSelected, boolean cellHasFocus) {
               JLabel resultat=new JLabel();
               resultat.setText(value.toString());
               resultat.setIcon(value.etatclient());
               
               if(isSelected)
               {
                   
                   
                   resultat.setBackground(Color.CYAN);
               }
               else 
               {
                   resultat.setBackground(list.getBackground());
               }
               
               resultat.setEnabled(list.isEnabled());
        
              resultat.setOpaque(true);

               return resultat;
               
           }
       });
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlistIhm = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        affichageContenu = new javax.swing.JTextArea();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jScrollPane4.setHorizontalScrollBar(null);

        jlistIhm.setBackground(new java.awt.Color(221, 213, 236));
        jlistIhm.setModel(listModelIhm);
        jlistIhm.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jlistIhm.setVisibleRowCount(-1);
        jScrollPane4.setViewportView(jlistIhm);

        affichageContenu.setEditable(false);
        affichageContenu.setColumns(20);
        affichageContenu.setRows(5);
        jScrollPane5.setViewportView(affichageContenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea affichageContenu;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList jlistIhm;
    // End of variables declaration//GEN-END:variables
}
