/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;


/**
 *
 * @author bah
 */
public class MsgPrive extends javax.swing.JFrame {
    private String style;
    private String nomClient;

    /**
     * Creates new form MsgPrive
     */
   
    private Connection connexion; 
    public MsgPrive(String nomClient) {
        initComponents();
        this.nomClient = nomClient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        scrollpaneSaisie = new javax.swing.JScrollPane();
        zoneDeSaisie = new javax.swing.JTextArea();
        bt_ajouter = new javax.swing.JButton();
        Normal = new javax.swing.JRadioButton();
        Gras = new javax.swing.JRadioButton();
        Italique = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 190));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        scrollpaneSaisie.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpaneSaisie.setFocusable(false);
        scrollpaneSaisie.setHorizontalScrollBar(null);

        zoneDeSaisie.setColumns(20);
        zoneDeSaisie.setRows(5);
        scrollpaneSaisie.setViewportView(zoneDeSaisie);

        bt_ajouter.setText("Envoyer");
        bt_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ajouterActionPerformed(evt);
            }
        });

        buttonGroup1.add(Normal);
        Normal.setText("Normal");
        Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalActionPerformed(evt);
            }
        });

        buttonGroup1.add(Gras);
        Gras.setText("Gras");
        Gras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrasActionPerformed(evt);
            }
        });

        buttonGroup1.add(Italique);
        Italique.setText("Italique");
        Italique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItaliqueActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("TlwgTypewriter", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(54, 36, 209));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/stri/tchat/strilogo_opt(1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Normal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Italique))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollpaneSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_ajouter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_ajouter)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Normal)
                    .addComponent(Gras)
                    .addComponent(Italique))
                .addGap(9, 9, 9)
                .addComponent(scrollpaneSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ajouterActionPerformed
        // TODO add your handling code here: ici envoyer un message au client

        String idmembre1 = new String();
        String idmembre2 = new String();
        String login=new String();
        String nomClient = new String();
        ArrayList <String>listMessag=new ArrayList<>();

        String texte=new String();
        texte=zoneDeSaisie.getText();

        // String requeteIdmembre1="Select id_membre from utilisateur where nomClient";
        String requeteIdmembre1="Select id_membre from utilisateur where login='bah'";

        try {
            Statement instruction = connexion.createStatement();
            ResultSet resultat = instruction.executeQuery(requeteIdmembre1);

            while (resultat.next())
            {

                idmembre1=resultat.getString("id_membre");
                System.out.println(idmembre1);
            }

        } catch (Exception e) {

        }

        // String requetidmembre2="select id_membre from utilisateur where login";
        String requeteidmembre2="Select id_membre from utilisateur where login='diallo'";
        try {
            Statement instruction = connexion.createStatement();
            ResultSet resultat = instruction.executeQuery(requeteidmembre2);

            while (resultat.next())
            {

                idmembre2=resultat.getString("id_membre");
                System.out.println(idmembre2);

            }

        } catch (Exception e) {

        }

        /*requete envoie message*/
        String requeteInsertion="INSERT INTO messageprive VALUES";
        requeteInsertion+="("+idmembre1+","+idmembre2+","+"CURRENT_TIMESTAMP"+",'"+texte+"')";

        try {
            Statement instruction = connexion.createStatement();
            ResultSet resultat = instruction.executeQuery(requeteInsertion);
            resultat.close();

        } catch (Exception e) {

        }
        /*recuperer message */
        String reqrecupmsg="Select message from messageprive where ='bah'";

        try {
            Statement instruction = connexion.createStatement();
            ResultSet resultat = instruction.executeQuery(reqrecupmsg);

            while (resultat.next())
            {

                idmembre1=resultat.getString("id_membre");
                System.out.println(idmembre1);
            }

        } catch (Exception e) {

        }
        /*MsgPrive client  = new MsgPrive(nomClient);
        client.setVisible(true);
        client.jTextArea1.setText(texte);*/

    }//GEN-LAST:event_bt_ajouterActionPerformed

    private void NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalActionPerformed
        // TODO add your handling code here:
        if(Normal.isSelected())
        {
            this.style="normale";
        }
    }//GEN-LAST:event_NormalActionPerformed

    private void GrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrasActionPerformed
        // TODO add your handling code here:
         if(Gras.isSelected())
          {
              
              this.style="gras";
          }
          
        
    }//GEN-LAST:event_GrasActionPerformed

    private void ItaliqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItaliqueActionPerformed
        // TODO add your handling code here:
        if(Italique.isSelected())
        {
            this.style="italique";
        }
    }//GEN-LAST:event_ItaliqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MsgPrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MsgPrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MsgPrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MsgPrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new MsgPrive().setVisible(true);
            }
       
                });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Gras;
    private javax.swing.JRadioButton Italique;
    private javax.swing.JRadioButton Normal;
    private javax.swing.JButton bt_ajouter;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane scrollpaneSaisie;
    private javax.swing.JTextArea zoneDeSaisie;
    // End of variables declaration//GEN-END:variables
}
